dist: bin

builds:
- dir: cmd
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/autocomplete.sh

source:
  enabled: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  skip: true

brews:
  - tap:
      owner: maiko
      name: homebrew-sshed-v2
    commit_author:
      name: Maiko BOSSUYT
      email: hello@maiko-bossuyt.eu
    homepage: https://github.com/maiko/sshed
    install: |
        bin.install "sshed"
        bash_completion.install "completions/autocomplete.sh"
      
scoop:
  bucket:
    owner: maiko
    name: scoop-sshed
  commit_author:
    name: Maiko BOSSUYT
    email: hello@maiko-bossuyt.eu
  homepage: https://github.com/maiko/sshed

nfpms:
  -
    homepage: https://github.com/maiko/sshed
    maintainer: Maiko BOSSUYT <hello@maiko-bossuyt.eu>
    formats:
      - deb
      - rpm
