dist: bin

builds:
- dir: cmd
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/autocomplete.sh

source:
  enabled: false

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  skip: true

nfpms:
  -
    homepage: https://github.com/maiko/sshed
    maintainer: Maiko BOSSUYT <hello@maiko-bossuyt.eu>
    formats:
      - deb
      - rpm
