name: Release
on:
  create:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Set up Go
        uses: actions/setup-go
        with:
          go-version: 1.21.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action
        with:
          version: v0.157.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GORELEASER_TOKEN}}
          GOPATH: /home/runner/go
